### ISSUE TITLE
Mime-types desconhecidos

### ISSUE THREAD

**Issue by dptole** [amirelemam/simpleServer#1]
@amirelemam Primeiramente parabéns pelo repo, é muito bom aprender uma linguagem nova explorando as possibilidades livremente.

Mas vamos direto ao problema.

Pela forma como o servidor foi feito os arquivos com extensão "html", "jpg", "jpeg", "png", "js" ou "css", dentro da pasta do arquivo "server.js", devem ser servidos.

Um erro ocorre quando tento acessar `http://localhost:3000/README.md` ou `http://localhost:3000/package.json`. Os dois arquivos existem dentro da pasta e a extensão não é válida, mas não existe um tratamento para o erro:

```
Loading /README.md
_http_outgoing.js:436
      throw new Error('Header "%s" value must not be undefined', key);
      ^

Error: Header "%s" value must not be undefined
    at storeHeader (_http_outgoing.js:436:13)
    at ServerResponse._storeHeader (_http_outgoing.js:353:7)
    at ServerResponse.writeHead (_http_server.js:253:8)
    at Server.http.createServer (/home/dan/lab/simpleServer/server.js:41:13)
    at emitTwo (events.js:126:13)
    at Server.emit (events.js:214:7)
    at parserOnIncoming (_http_server.js:602:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
```

> Quando isso acontece o servidor fica fora do ar.

Esse erro acontece pois "md" ou "json" não existem como chaves da variável `mimeTypes` e por isso quando o servidor tenta criar o cabeçalho "Content-type" o erro é lançado:

```javascript
res.writeHead(200, {
    'Content-type': mimeType, // mimeType é undefined
});
```

Talvez a solução mais simples seja retornar algo como

```
res.writeHead(400, {
    'Content-type': 'text/plain'
});
res.write('Invalid file type\n');
res.end()
```

**Comment by amirelemam** [comment]
Obrigado, Danillo!
Realmente, este erro é grave e deveria ter sido evitado.
Sua solução resolve o problema.
Já testei e incluí no código.
Obrigado!
